name: build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.3.0
      uses: actions/setup-node@v1
      with:
        node-version: '16.3.0'
    - name: Install npm
      run: |
        npm uninstall bcrypt
        npm install bcrypt
        npm install
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: capuzR/bRNodeServer/build
        registry: docker.pkg.github.com
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: dockerfile.prod
        tags: latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DIGITAL_OCEAN_IP }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        key: ${{ secrets.DIGITAL_OCEAN_KEY }}
        passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
        envs: GIT_USERNAME, GITHUB_TOKEN
        script: |
          docker stop brnodeserver
          docker rm brnodeserver
          docker login docker.pkg.github.com -u $GIT_USERNAME -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/capuzr/brnodeserver/build:latest
          docker run -itd --name brnodeserver -p 80:5000 docker.pkg.github.com/capuzr/brnodeserver/build:latest
